name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
          HOSTNAME: ${{ secrets.HOSTNAME }}
          USER_NAME: ${{ secrets.USER }}

        run: |
          echo "PRIVATE_KEY: $PRIVATE_KEY"
          echo "HOSTNAME: $HOSTNAME"
          echo "USER_NAME: $USER_NAME"

           
            cd /home/ubuntu/react-ssr/
            git clone https://github.com/ANJALI-1233/react-ssr.git
            npm install
            npm run dev
            # Add more deployment steps as needed
          
